<?php

return [
    'primary_institutions' => [
        'Adventist Medical Center - Manila',
        'Amang Rodriguez Memorial Medical Center',
        'Asian Hospital and Medical Center',
        'Capitol Medical Center',
        'Cardinal Santos Medical Center',
        'Chinese General Hospital and Medical Center',
        'De Los Santos Medical Center',
        'Dr. Jesus Delgado Memorial Hospital',
        'Dr. Jose Fabella Memorial Hospital',
        'Dr. Jose N. Rodriguez Memorial Hospital and Sanitarium',
        'East Avenue Medical Center',
        'Fatima University Medical Center',
        'Fe Del Mundo Medical Center',
        'Healthway FEU-NRMF Medical Center',
        'Hospital of the Infant Jesus',
        'Jose Reyes Memorial Medical Center',
        'Las Piñas Doctors Hospital',
        'Las Piñas General Hospital & Satellite Trauma Center',
        'Makati Medical Center',
        'Mandaluyong City Medical Center',
        'Manila Central University - Filemon D. Tanchoco Sr. Medical Foundation, Inc.',
        'Manila Doctors Hospital',
        'Mary Chiles General Hospital',
        'Mary Johnston Hospital',
        'Medical Center Manila',
        'Medical Center Muntinlupa, Inc.',
        'Medical Center Parañaque',
        'Metro Antipolo Hospital and Medical Center',
        'Metropolitan Medical Center',
        'National Children\'s Hospital',
        'Ospital ng Makati',
        'Ospital ng Muntinlupa',
        'Our Lady of Lourdes Hospital',
        'Pasay City General Hospital',
        'Pasig City Children\'s Hospital - Child\'s Hope',
        'Pasig City General Hospital',
        'Perpetual Help Medical Center - Las Piñas',
        'Philippine Children\'s Medical Center',
        'PLM-Ospital ng Maynila Medical Center',
        'Quezon City General Hospital',
        'Quirino Memorial Medical Center',
        'Rizal Medical Center',
        'San Juan De Dios Hospital',
        'San Juan Medical Center',
        'Sta. Ana Hospital',
        'St. Luke\'s Medical Center - Global City',
        'St. Luke\'s Medical Center - Quezon City',
        'The Medical City',
        'Tondo Medical Center',
        'UERM- Medical Center',
        'University of Santo Tomas Hospital',
        'University of the Philippines - Philippine General Hospital',
        'Valenzuela Medical Center',
        'Veterans Memorial Medical Center',
        'Victoriano Luna Medical Center',
        'VRP Medical Center',
        'World Citi Medical Center',
        'Philippine Heart Center',
        'Research Institute for Tropical Medicine',
        'Cagayan Valley Medical Center',
        'Region II Trauma and Medical Center',
        'Southern Isabela Medical Center',
        'Baguio General Hospital & Medical Center',
        'Ilocos Training and Regional Medical Center',
        'Mariano Marcos Memorial Hospital & Medical Center',
        'Region I Medical Center',
        'Saint Louis University – Sacred Heart Medical Center',
        'Angeles University Foundation Medical Center',
        'Bataan General Hospital and Medical Center',
        'Bulacan Medical Center',
        'Central Luzon Doctors Hospital',
        'Dr. Paulino J. Garcia Memorial Research & Medical Center',
        'James L. Gordon Memorial Medical Center',
        'Jecsons Medical Center',
        'Jose B. Lingad Memorial General Hospital',
        'Tarlac Provincial Hospital',
        'Batangas Medical Center',
        'Gen. Emilio Aguinaldo Memorial Hospital',
        'Mary Mediatrix Medical Center',
        'Perpetual Help Medical Center - Biñan',
        'Ospital ng Palawan',
        'De La Salle University Medical Center',
        'Bicol Medical Center',
        'Bicol Regional Hospital & Medical Center',
        'Bicol Region General Hospital and Geriatric Medical Center',
        'Cebu City Medical Center',
        'Cebu Doctor\'s University Hospital',
        'Cebu South Medical Center',
        'Cebu Velez General Hospital',
        'Chong Hua Hospital - Mandaue',
        'Eversley Childs Sanitarium & General Hospital',
        'Governor Celestino Gallares Hospital',
        'Perpetual Succour Hospital',
        'Silliman University Medical Center',
        'Southwestern University Medical Center',
        'University of Cebu Medical Center',
        'VisayasMed Hospital',
        'Chong Hua Hospital',
        'Vicente Sotto Memorial Medical Center',
        'Allied Care Expert (ACE) Medical Center-Tacloban',
        'Divine Word Hospital',
        'Eastern Visayas Medical Center',
        'Doña Remedios Trinidad Romualdez Educational Foundation',
        'Adventist Medical Center - Bacolod',
        'Corazon Locsin Montelibano Memorial Hospital',
        'Riverside Medical Center, Inc. (Dr. Pablo O. Torre Sr. Memorial Hospital)',
        'The Doctor\'s Hospital, Inc.',
        'Iloilo Doctor\'s Hospital',
        'Iloilo Mission Hospital',
        'St. Paul\'s Hospital Iloilo',
        'West Visayas State University Medical Center',
        'Western Visayas Medical Center',
        'Southern Philippines Medical Center',
        'Brokenshire Medical Center',
        'Cotabato Regional & Medical Center',
        'Davao Doctor\'s Hospital',
        'Davao Medical School Foundation Hospital',
        'Davao Regional Medical Center',
        'Metro Davao Medical and Research Center, Inc.',
        'General Santos Doctor\'s Hospital',
        'San Pedro Hospital of Davao',
        'St. Elizabeth Hospital, Inc.',
        'Adventist Medical Center - Iligan',
        'Maria Reyna Xavier University Hospital',
        'Mayor Hilarion A. Ramiro Senior Medical Center',
        'Northern Mindanao Medical Center',
        'Amai Pakpak Medical Center',
        'Zamboanga City Medical Center',
    ],
    'specialties' => [
        'Child Neurology Society of the Philippines (CNSP)',
        'Society of Pediatric Critical Care Medicine Philippines (SPCCMP)',
        'Philippine Society of Pediatric Oncology (PSPO)',
        'Pediatric Nephrology Society of the Philippines, Inc. (PNSP)',
        'Philippine Academy of Pediatric Pulmonologists, Inc. (PAPP)',
        'Philippine Society of Newborn Medicine (PSNbM)',
        'Philippine Society for Developmental and Behavioral Pediatrics (PSDBP)',
        'Pediatric Infectious Disease Society of the Philippines (PIDSP)',
        'Philippine Society of Pediatric Metabolism and Endocrinology (PSPME)',
        'Philippine Society of Pediatric Cardiology (PSPC)',
        'Philippine Society for Pediatric Gastroenterology, Hepatology and Nutrition (PSPGHaN)',
        'Philippine Society of Pediatric Hematology (PSPH)',
        'Philippine Society of Adolescent Medicine Specialist (PSAMS)',
        'Ambulatory Pediatrics',
        'Allergy, Asthma and Immunology',
        'Community Pediatrics',
        'Clinical Genetics',
        'Pediatric Rheumatology',
        'Philippine Society of Pediatric Surgeons (PSPS)',
        'Philippine Pediatric Dental Society, Inc. (PPDS)',
        'Pediatric and Adolescent Gynecology Society of the Philippines (PAGSPHIL)',
    ],
];
