location ~* ^/(vendor|lib|phpunit|laravel|www|ws|yii|zend|tests?|testing|api|demo|cms|crm|admin|backup|blog|workspace|panel|public|apps?)/.*\.php$ {
    deny all;
    return 404;
}

location ~* ^/(upl|1|password|shell|cmd|c99|r57|webshell)\.php$ {
    deny all;
    return 404;
}

location ~* eval-stdin\.php$ {
    deny all;
    return 404;
}

location ~* /index\.php\?s=/index/\\think {
    deny all;
    return 404;
}

location ~* /(\.git|\.env|\.htaccess|web\.config|composer\.(json|lock)|package\.json|yarn\.lock) {
    deny all;
    return 404;
}

location ~* ^/storage/(?!app/public/) {
    deny all;
    return 404;
}

location ~* ^/bootstrap/cache {
    deny all;
    return 404;
}